version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: x_pear_db
      POSTGRES_USER: django
      POSTGRES_PASSWORD: 24pearStr.
    ports:
      - "5432:5432"